### ISSUE TITLE
Not accepting requests, throwing 500 error.

### ISSUE THREAD

**Issue by romeojulietthotel** [rmed/akamatsu#26]
Running in develop mode.

`AKAMATSU_CONFIG_FILE=./development.py akamatsu run`

Request returns a 500 error.

```
[2018-11-12 14:18:27,221] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/py/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/py/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
```

**Comment by rmed** [comment]
Hi, I haven't updated the setup.py in a while, so some things may have broken over time. Try this:

```
AKAMATSU_CONFIG=development.py FLASK_APP=akamatsu:init_app flask run
```
